### ISSUE TITLE
[求助]生成的图片分页问题

### ISSUE THREAD

**Issue by yangg** [palxiao/poster-design#121]
我们现在有下面两个需求，希望能分别给出一些实现思路，谢谢！！

假如我们设计一个 400*1500 的图，需要分页
分页后每页只显示 600 的高度， 并且可以设置页头和页脚，有可能将一个长的文字拆分到不同页面。
两个需求：
1.生成1张大图片，里面需要下面这样并排着大概 4 页小图
<img width="417" alt="image" src="https://github.com/palxiao/poster-design/assets/409225/f8826f08-b848-4d18-8d56-bb751216bd68">
2. 生成 1 个 pdf，pdf 有 4页，都包含页头和页脚

**Comment by palxiao** [comment]
这个我可能给不了什么建议或帮助，感觉需求不是图片编辑器的范畴，像是一个word文档编辑器

**Comment by yangg** [comment]
> 这个我可能给不了什么建议或帮助，感觉需求不是图片编辑器的范畴，像是一个word文档编辑器

好的，Thanks anyway!
