### ISSUE TITLE
打开模板后未编辑就点其它模板时，会出现确认提示

### ISSUE THREAD

**Issue by yangg** [palxiao/poster-design#124]
1. 打开模板后未编辑就点其它模板时，会出现确认提示，这时这个提示是否多余，能否修复下，好像是历史记录判断出错了？
2. 切换模板时 page.name 那个文本框里的值不会切换。
3. 图层列表的最下面一下，点击右键菜单显示不完整。

**Comment by palxiao** [comment]
1. 对于提示框的交互增加了“不再提示”按钮
![image](https://github.com/palxiao/poster-design/assets/21021314/f8a0cd9b-7851-4b72-ba1f-b2d6de3bae37)
（其实本意是添加模板到画布中而非打开模板，只不过现在还没做这些逻辑和相关功能，可以参考稿定设计的交互：
![image](https://github.com/palxiao/poster-design/assets/21021314/92c69591-76da-45b3-84c7-7b33cde561ca)

2. 这个page.name相当于文件名，需要用户自己编辑。初始化模板时带入模板name的场景通常类似于在前置页面中点击进入。
3. bug，已记录

**Comment by palxiao** [comment]
fix: https://github.com/palxiao/poster-design/commit/22ecc9900da15caad78587c53ab5300cc1c43836
