### ISSUE TITLE
screenshot服务基于howard86/puppeteer_node:12镜像部署，截图效果不好

### ISSUE THREAD

**Issue by sizexl** [palxiao/poster-design#128]
网页上的图是这样的
![image](https://github.com/palxiao/poster-design/assets/14197558/8829268d-129b-4d2c-a8f4-d4202120ec2d)

截出来的图是这样的
![image](https://github.com/palxiao/poster-design/assets/14197558/d1968b5a-ad45-432c-96d8-9f80d1813967)
依赖版本
```
{
        "name": "screenshot-node-builder",
        "version": "1.0.0",
        "dependencies": {
          "body-parser": "1.19.0",
          "express": "4.17.1",
          "images": "3.2.4",
          "puppeteer": "10.4.0"
        }
}
```

用的是自动模式，原因如下：
经过调试发现，`download-single.ts` 中 `if (prevent === false) ` 这句判断在调用 `screenshots` 方法时是不走的，prevent === undefined
所以走到主动模式 `await page.exposeFunction('loadFinishToInject', async () => {` ，但这句不知道为什么没有运行，整个主动模式被跳过，接口直接返回 `Error: ENOENT: no such file or directory`
故修改 `prevent` 的默认值为 `false` 强行走了自动模式
不知道会不会跟这个有关

**Comment by palxiao** [comment]
生成海报使用的截图接口，与全屏网页截图是两个功能不同的接口。下载海报生成图片不支持自动模式
