### ISSUE TITLE
文字素材是怎样生成的？

### ISSUE THREAD

**Issue by liuxsen** [palxiao/poster-design#13]
如上

**Comment by palxiao** [comment]
将对应的 JSON Schema 保存成为预设，和模板保存是一样的

**Comment by liuxsen** [comment]
也是通过psd上传？跟模板的data一样？

**Comment by palxiao** [comment]
> 也是通过psd上传？跟模板的data一样？

跟模板的data是一样的，在保存时区分了类型

例如文字素材大部分都是“组合”组件（wGroup）

<img width="762" alt="image" src="https://github.com/palxiao/poster-design/assets/21021314/f1ccde3e-90ab-4b8b-93f8-0f9dedf0726a">

保存的就是这个组合的 Schema 结构

**Comment by liuxsen** [comment]
![image](https://github.com/palxiao/poster-design/assets/12598696/040a87b4-4bc3-4872-a5ee-daafcebbdb82)
为什么截屏失败？

**Comment by palxiao** [comment]
看输出信息应该是超时了，你在模板中只放一个文字看能不能生成

**Comment by palxiao** [comment]
可以在node层请求页面url上加个md5解决，模板详情绘制页将md5传递给后端解析后正常返回数据。或者在前端下载按钮时就带上鉴权token，node拼接到url上传递给绘制页你再处理下就好了。

**Comment by liuxsen** [comment]
> > 也是通过psd上传？跟模板的data一样？
> 
> 跟模板的data是一样的，在保存时区分了类型
> 
> 例如文字素材大部分都是“组合”组件（wGroup）
> 
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/21021314/259937393-f1ccde3e-90ab-4b8b-93f8-0f9dedf0726a.png">
> 保存的就是这个组合的 Schema 结构

字体文件有吗？

**Comment by palxiao** [comment]
网上有很多免费字体可以使用：

https://wordshub.github.io/free-font/

https://www.zitijia.com/

**Comment by liuxsen** [comment]
感谢回复这么快啊

**Comment by liuxsen** [comment]
> 

前端源码没看到这部分实现呢

**Comment by liuxsen** [comment]
> > 也是通过psd上传？跟模板的data一样？
> 
> 跟模板的data是一样的，在保存时区分了类型
> 
> 例如文字素材大部分都是“组合”组件（wGroup）
> 
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/21021314/259937393-f1ccde3e-90ab-4b8b-93f8-0f9dedf0726a.png">
> 保存的就是这个组合的 Schema 结构

前端源码没看到这部分实现呢

**Comment by palxiao** [comment]
前端没做素材管理，你可以像保存模板一样保存文字组件，只是类型改变而已，甚至保存模板和保存文字组件可以是同个接口，它们的数据是一样的，只是两者传的type不一样而已，前端也是通过取不同的类型做业务逻辑的判断的。
比如我的模板和组件就是同一个请求接口，只是我传的值不一样：
![image](https://github.com/palxiao/poster-design/assets/21021314/ce678a82-e60f-4ed9-9a4e-f5ca9fa05735)

**Comment by liuxsen** [comment]
> 

那这感觉不像是文字，反而是组件的意思，跟figma的组件一样
