### ISSUE TITLE
截图，字体加载可能导致有 loading 问题

### ISSUE THREAD

**Issue by iHTCboy** [palxiao/poster-design#130]
![screenshot](https://github.com/palxiao/poster-design/assets/11418363/8ccb2bcc-5361-4903-a874-024d027da5f2)

字段的加载动画，也截图在图片中了，怀疑是字段加载慢导致，这个怎么修复，可以延迟截图吗

**Comment by palxiao** [comment]
字体加载有30秒超时检查，可以尝试调大一点看看：
![image](https://github.com/palxiao/poster-design/assets/21021314/78769550-12b0-458a-b2ba-b869c2672cf8)

**Comment by iHTCboy** [comment]
<img width="653" alt="image" src="https://github.com/palxiao/poster-design/assets/11418363/3c5b5a6c-d9bb-4072-a2b6-b8a6e498594d">

@palxiao 大佬，我的意思是， 导出的图片中，字体下面有一个 loading 的背景，影响了图片

**Comment by palxiao** [comment]
是偶现还是必现？

**Comment by iHTCboy** [comment]
用在线的demo版本，正常：
![1714032493474](https://github.com/palxiao/poster-design/assets/11418363/34012de3-fa4a-4b26-b918-3111a4f61f47)

我本地跑的，测试几次，都会出现：
![1714032537486](https://github.com/palxiao/poster-design/assets/11418363/ba2aa647-1077-4cb4-a477-d2663106325e)

仔细对比，差异：
- 文字组件：还有白色背景
- loading 图

**Comment by iHTCboy** [comment]
@palxiao 大概问题知道了，是我挂 vpn，网络访问慢。去掉 vpn，现在截图是正常了，所以看看这个后续有没有可能优化啊
