### ISSUE TITLE
选择字体列表，被画布的滚动条遮挡了

### ISSUE THREAD

**Issue by iHTCboy** [palxiao/poster-design#133]
如图示例：

<img width="310" alt="image" src="https://github.com/palxiao/poster-design/assets/11418363/0142e82a-6339-442b-b2a2-a5847746c4af">

**Comment by palxiao** [comment]
![image](https://github.com/palxiao/poster-design/assets/21021314/13871b55-43db-4bda-9ecc-5868ce6b3957)

**Comment by palxiao** [comment]
好像复现不出来

**Comment by iHTCboy** [comment]
@palxiao 我知道了，用 Mac 的 safari 浏览器才有，谷歌浏览器显示正常
