### ISSUE TITLE
你好 请问下rembg是在后台使用的吗? 前端项目里我没发现有用到的地方

### ISSUE THREAD

**Issue by itmier** [palxiao/poster-design#14]
你好 请问下`rembg` 是在后台使用的吗? 前端项目里我没发现有用到的地方, 想研究下前端是否能做到删除图片背景?
<img width="892" alt="image" src="https://github.com/palxiao/poster-design/assets/59595216/40ffb192-c4f7-4ec3-8b80-035e1f1c1ff7">

**Comment by palxiao** [comment]
抠图是部署在服务端的，配置需求不高，我写了一篇部署的文章可以参考：https://juejin.cn/post/7264237761158873149

最近有看到一个前端的抠图库给你参考：https://github.com/imgly/background-removal-js，缺点也很明显，启动时需要在浏览器下载模型（似乎有差不多80M大小）
