### ISSUE TITLE
已有的文字素材和模板不满足需求，如何新增呢？

### ISSUE THREAD

**Issue by fantasy525** [palxiao/poster-design#143]
我们这里想自己设计自己的文字，素材，和模板，这个有没有教程或者方便这里说下吗

**Comment by QianSu** [comment]
同问

**Comment by palxiao** [comment]
> 同问

模板由设计师制作psd设计图，导入修改后上传，目前增加了导入模板和组件的完整示例

![daoru (1)](https://github.com/user-attachments/assets/9a70ee26-d16b-490a-ae05-709f2a329436)
