### ISSUE TITLE
最终的合成图片能否纯前端实现？

### ISSUE THREAD

**Issue by jujusharp** [palxiao/poster-design#15]
我看系统最终合成图片的方案是通过chrome的无头方式实现的，我看你在文档中也提到了Html2Canvas，想请问下，能否用更轻量级html2canvas方案？是否由于html2canvas的生成效果不太好？

**Comment by palxiao** [comment]
html2canvas的原理是通过JS解析目标DOM树然后”翻译“成Canvas语法绘制，借由Canvas API出图，有几个明显缺点，比如绘制成Canvas后图片可能会失真（锯齿、模糊等情况），比如有很多CSS特性不支持（如渐变色、文字特效等），还有画布中使用了SVG等元素更不支持解析，所以前端出图在应对复杂场景时工作量难以预估，只有在特别简单的场景下：例如只有图片和最简单的文字构成的海报可以考虑从前端直接出图。服务端Chrome截图方式没有这种”翻译“的过程，能在最少开发成本下保证出图准确度和质量。

**Comment by jujusharp** [comment]
好的，感谢回复
