### ISSUE TITLE
screenshot服务基于howard86/puppeteer_node:12镜像下载失败

### ISSUE THREAD

**Issue by wangyuan389** [palxiao/poster-design#151]
![image](https://github.com/user-attachments/assets/8197a245-547a-4c06-be9c-3a84cee0de65)
你好，linux多次下载howard86/puppeteer_node:12均失败，能否提供一份dockerFile配置，我本地创建镜像部署下试试

**Comment by palxiao** [comment]
没有写dockerFile，可以参考readme文件中手动打包的说明来部署：https://github.com/palxiao/poster-design/tree/main/screenshot#%E6%89%93%E5%8C%85

**Comment by palxiao** [comment]
最近发现docker镜像源目前在国内已经无法访问了，包括阿里网易等加速源也无法使用，可能是这个原因造成的，该问题关闭
