### ISSUE TITLE
无法点击成组

### ISSUE THREAD

**Issue by wangxiaoweigood** [palxiao/poster-design#154]
拉下本地代码 运行起来 上传本地模板后 无法使用成组 报错  但是线上版本 是完全可以使用的
![image](https://github.com/user-attachments/assets/a817e895-1136-4dca-9905-dd1fc01aa1ba)
![image](https://github.com/user-attachments/assets/c4d64b6a-2ee3-430e-b4e6-71d092a5fce1)

**Comment by palxiao** [comment]
缺少引用，已修复

fix: https://github.com/palxiao/poster-design/commit/1b704ee1d283754808be72dcb9585533ad0b367e
