### ISSUE TITLE
能否补一下lock文件

### ISSUE THREAD

**Issue by swordsman-coder** [palxiao/poster-design#16]
作者可以补下lock文件吗，目前依赖的版本不受控。盼望😄

**Comment by palxiao** [comment]
有几个dev依赖似乎存在问题，暂时还没解决，无法正常安装。

**Comment by palxiao** [comment]
你试下使用 npm i --force 应该是能成功的，和lock文件无关

**Comment by palxiao** [comment]
我试了下安装依赖确实报错了，是因为我昨天更新了@palxp/color-picker这个组件，可能加速镜像npmmirror还没同步导致找不到版本号。你可以尝试切换到npm原始镜像源安装，或者在package.json移除后单独安装这个包。

**Comment by swordsman-coder** [comment]
> 我试了下安装依赖确实报错了，是因为我昨天更新了@palxp/color-picker这个组件，可能加速镜像npmmirror还没同步导致找不到版本号。你可以尝试切换到npm原始镜像源安装，或者在package.json移除后单独安装这个包。

已经安装成功🎉🎉🎉

这个倒是问题不大，但还是建议补充下node版本和lock。否则如果alloy和ts升级后，对后续的新进来的开发会有影响，也不利于你项目的传播不是😄

还有就是@gradio/client，我看着这个东西对node版本也是有要求的，如果如果要使用抠图的话 建议补充下node版本要求。我没这部分需要，就直接去掉了，省的再折腾版本。另外问下抠图是用的rembg吗

**Comment by palxiao** [comment]
刚刚我试了一下，使用pnpm安装全程正常。。打算修改一下文档了。

@gradio/client这个是用于项目中抠图那部分websocket请求的封装，它不知为何限制了node18版本（其实不是18也正常运行的），我的环境是 16.18 以上就可以了（这在readme文档我都有说明），之前就是因为这个库的冲突才强制安装。

**Comment by palxiao** [comment]
> > 我试了下安装依赖确实报错了，是因为我昨天更新了@palxp/color-picker这个组件，可能加速镜像npmmirror还没同步导致找不到版本号。你可以尝试切换到npm原始镜像源安装，或者在package.json移除后单独安装这个包。
> 
> 已经安装成功🎉🎉🎉
> 
> 这个倒是问题不大，但还是建议补充下node版本和lock。否则如果alloy和ts升级后，对后续的新进来的开发会有影响，也不利于你项目的传播不是😄
> 
> 还有就是@gradio/client，我看着这个东西对node版本也是有要求的，如果如果要使用抠图的话 建议补充下node版本要求。我没这部分需要，就直接去掉了，省的再折腾版本。另外问下抠图是用的rembg吗

是的，文档中有说明rembg的安装，这个使用也挺容易的。

https://juejin.cn/post/7264237761158873149
