### ISSUE TITLE
怎么解决下载的海报有加载状态？

### ISSUE THREAD

**Issue by linfayi** [palxiao/poster-design#161]
![image](https://github.com/user-attachments/assets/d32b0b63-bc13-4212-b987-807259846b36)

**Comment by palxiao** [comment]
字体加载的loading可能在动画执行过程中截图，可以适当延长draw.vue中loadFinishToInject执行的延迟，将100毫秒增加到300以上能解决问题

不过这个应该是旧的项目才会，现在已经移除截图状态下loading的展示了

**Comment by palxiao** [comment]
fix: https://github.com/palxiao/poster-design/commit/b224f44f6836c4343fb8bb57900d6e2c37262fd1
