### ISSUE TITLE
标尺功能

### ISSUE THREAD

**Issue by KID-1912** [palxiao/poster-design#162]
标尺功能为什么注掉了，是哪里有问题吗
![image](https://github.com/user-attachments/assets/3a3c84a3-7709-44b1-9ba1-6eb2fd8bea9b)

**Comment by KID-1912** [comment]
注意到movable官方示例已实现 【标尺】https://daybrush.com/moveable/

**Comment by palxiao** [comment]
只是注释掉图标，迁移到文件选项中
![image](https://github.com/user-attachments/assets/215c9201-073c-453a-aaa8-f8bf9e103207)
