### ISSUE TITLE
大佬，demo网站示例，代码是不是没有同步到最新

### ISSUE THREAD

**Issue by iHTCboy** [palxiao/poster-design#163]
发现一些交互，在网页有，但是demo上没有找到。比如素材搜索功能：

<img width="420" alt="image" src="https://github.com/user-attachments/assets/ebcd63ca-b9ba-4b59-9e11-6e44b3558a5c">

**Comment by palxiao** [comment]
这类业务功能其实不属于编辑器本身的范畴了
