### ISSUE TITLE
模板里的图片，鼠标移入就会消失

### ISSUE THREAD

**Issue by xintianyou** [palxiao/poster-design#164]
![image](https://github.com/user-attachments/assets/b683b3d3-00c9-4053-8153-f258a3be7fbe)

官网没这个问题

**Comment by xintianyou** [comment]
使用模板，鼠标移入时会报图片的跨域错误
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/81ac2979-c682-493e-a3a8-cee147869e2e">
自己制作的不会

**Comment by palxiao** [comment]
演示的模板里图片链接存放在第三方，目前访问似乎有点问题，并非代码bug
