### ISSUE TITLE
组合经过缩放和调整角度后，下载的图片位置和画板内容不一致

### ISSUE THREAD

**Issue by lIdeazZ** [palxiao/poster-design#165]
![image](https://github.com/user-attachments/assets/ba07834d-f648-4daf-86fd-3a99cf8b25e6)
![作品名](https://github.com/user-attachments/assets/51526bae-5443-42dd-8b59-260fd2d08093)

地址：官网
操作步骤：选中组合  => 缩放 => 旋转 => 下载

看了仓库代码，感觉是transformOrigin的问题

**Comment by palxiao** [comment]
可以复现，我会尽快查看问题，感谢反馈

**Comment by palxiao** [comment]
https://github.com/palxiao/poster-design/commit/e07a5cefe1722102cc079808d80955585e8e2435
