### ISSUE TITLE
服务端的并发量

### ISSUE THREAD

**Issue by houchaowei** [palxiao/poster-design#17]
想问下 puppeteer启动屋头浏览器还是比较占内存的，有测试过已知服务器内核和内存的情况下的服务端截图的并发量吗？

**Comment by palxiao** [comment]
puppeteer是比较吃cpu和内存的，所以代码里做了队列、并发阈值和熔断等处理。我的在线Demo跑在1h2g的服务器上（并且还跑了其它服务），运行到目前都在稳定状态。一般规格的海报之前在公司测试4h8G单服务器并发大概能稳定20~30张左右（场景是后端一次循环发起了400次下载没失败）。反正用户规模小的情况下无论如何都够用，真有非常大的用户规模才考虑并发问题，那时肯定是需要集群服务器的。

**Comment by houchaowei** [comment]
<img width="850" alt="image" src="https://github.com/palxiao/poster-design/assets/17643027/484b44d1-cda5-40c8-b1bb-50e922d3753a">
我今天在我本地跑 ab 去测试，发现存在失败的情况，但是这个里面的 failed requests 的次数和获取到的图片的次数还不一样，ab 提示的是失败了 15 次，跑 20 次请求，附带缩略图，返回了 32 张图，也就是说成功了 16 次，实际上上是失败了 4 次，但是没有错误提示，我本机是 M1 顶配 32g 内存

**Comment by palxiao** [comment]
printscreen 这个接口我没怎么测试过，刚验证了下，因为这个文件是以时间戳为命名来保存的，没考虑到当并发时可能存在前后两张图的时间戳刚好一致，造成了覆盖，所以你才会看到图片数量不一致的问题。所以只需要修改代码中逻辑（例如加个随机数：const path = filePath + `screenshot_${new Date().getTime()}_${Math.random()}.png`），生成的数量结果就正常了。

至于本地ab测试为什么会显示failed request这个问题尚不明确（猜测可能是express的sendFile方法有什么问题？）

理论上Complete requests就是全部请求成功了，我在测试时中途手动通过浏览器访问穿插一条请求结果也是符合预期的。

**Comment by houchaowei** [comment]
今天测试的时候确实存在时间戳重复的问题，在并发多的情况下：
<img width="420" alt="image" src="https://github.com/palxiao/poster-design/assets/17643027/9bdadc45-f2b2-4b43-8a7c-4b7dffbf3936">
后缀和 sign 增加 uuid 的情况下，在处理超过 20 条并发时，还是会出现请求丢失的问题，还在排查中。。。

**Comment by houchaowei** [comment]
> 今天测试的时候确实存在时间戳重复的问题，在并发多的情况下： <img alt="image" width="420" src="https://user-images.githubusercontent.com/17643027/264949534-9bdadc45-f2b2-4b43-8a7c-4b7dffbf3936.png"> 后缀和 sign 增加 uuid 的情况下，在处理超过 20 条并发时，还是会出现请求丢失的问题，还在排查中。。。

<img width="1540" alt="image" src="https://github.com/palxiao/poster-design/assets/17643027/dac3ac82-7261-486f-9e04-1020329c8d6f">

**Comment by houchaowei** [comment]
<img width="1485" alt="image" src="https://github.com/palxiao/poster-design/assets/17643027/dd6c921c-49b1-4274-9198-a7491350d343">
node-queue.ts下的 queueRun 确实存在问题，如图，当请求并发数多的时候，入和 run 的个数对不上，怀疑这段代码有问题，带还不知道怎么优化：

```
if (curNum >= maxNum) {
  queueList.push({ sign, Fn })
} else {
  await run(Fn)
}
```
