### ISSUE TITLE
图片合成后端是用什么来实现的

### ISSUE THREAD

**Issue by pjsqwerty** [palxiao/poster-design#2]
保存数据合成图片后端是采用的怎样的方式, 有没有项目参考一下 大佬

**Comment by palxiao** [comment]
你好，服务端是基于puppeteer截图生成图片，项目后续会完整开源，最近比较忙

**Comment by palxiao** [comment]
https://github.com/palxiao/poster-design/tree/main/screenshot

**Comment by palxiao** [comment]
代码已上传，图片生成服务：https://github.com/palxiao/poster-design/tree/main/screenshot
