### ISSUE TITLE
moveable的位置如何跟随数据变化

### ISSUE THREAD

**Issue by swordsman-coder** [palxiao/poster-design#20]
然后尝试了图片的 发现moveable的选择框有跟随数据保持一致。
没有发现moveable关联位置的地方，这块是怎么实现的呢。

另外我又尝试了笔刷（svg），在右侧编辑区 改动笔刷的位置尺寸的位置和宽高，却发现未出现跟随效果。

期待回复

**Comment by palxiao** [comment]
目前moveable和数据之间是解耦的，数据更新时没有相关监听者响应moveable的更新，所以没跟随。

如果要让moveable响应DOM变化，可以在需要时调用其实例的方法：moveable.updateRect() 主动更新

**Comment by swordsman-coder** [comment]
感谢，另外你可以看下svg笔刷，moveable是没有响应DOM变化的
![image](https://github.com/palxiao/poster-design/assets/16441180/dec91def-2dee-4460-9590-535395488b35)

**Comment by palxiao** [comment]
嗯，这个组件里是没处理，稍后我修复更新一下
