### ISSUE TITLE
项目优化等常见问题

### ISSUE THREAD

**Issue by rayadaschn** [palxiao/poster-design#21]
- 域名更替后，[中文文档网站](https://xp.palxp.cn/) 等打开失败
- 仓库建议 Discussion 讨论，便于更好的提问，如可探讨是否加入 i18n 国际化等。项目流程化也更为清晰：Discussion -> Issues -> Pull requests

**Comment by palxiao** [comment]
感谢支持和建议，已开通 Discussion.
