### ISSUE TITLE
Failed to resolve import "./base" from "src/router/index.ts". Does the file exist?

### ISSUE THREAD

**Issue by AliceQAQ** [palxiao/poster-design#23]
[vite] Internal server error: Failed to resolve import "./base" from "src/router/index.ts". Does the file exist?

有四个ts文件因文件名大小写问题导致项目启动报错，更名后启动正常。

**Comment by palxiao** [comment]
可否指明其它三个文件名称，我在本地启动没有报错难以发现异常

**Comment by AliceQAQ** [comment]
抱歉，可能因为我用的是nodejs20的版本以及构建平台是ArchLinux，我目前在Windows上使用nodejs18构建完成后没有异常，可以正常运行，感谢您的回复。
