### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'D:\project\poster-design\screenshot\static\13-screenshot.png'

### ISSUE THREAD

**Issue by jhaEffort** [palxiao/poster-design#24]
您好 自己本地启动的服务 自己的api但是 下载图片时提示没有下载成功。幸苦回复

**Comment by palxiao** [comment]
确认 screenshot 服务有启动吗

**Comment by palxiao** [comment]
window系统的话手动进项目中的 /screenshot 目录启动 node 服务

**Comment by jhaEffort** [comment]
您好启动了 启动是提示这个 也按照代码里面的 创建了/static/文件了

**Comment by palxiao** [comment]
有无相关截图看下

**Comment by jhaEffort** [comment]
![image](https://github.com/palxiao/poster-design/assets/46337068/8ef533f7-4676-4d8a-8276-ad384f8d8338)
您好 辛苦看下！ 您方便看微信吗
