### ISSUE TITLE
你好，请问什么时间会有文字特效编辑的功能呢？

### ISSUE THREAD

**Issue by StoneRyanCn** [palxiao/poster-design#36]
我在测试环境中看到有文字特效的编辑功能，但是下载源码运行后却没有此功能 ，请问这个功能将会在什么时间发布呢 @palxiao @rayadaschn 

![image](https://github.com/palxiao/poster-design/assets/15223927/ecb14613-1c64-48ab-80d7-10f392f5b7d5)

**Comment by palxiao** [comment]
还在测试中，今天会发布
