### ISSUE TITLE
截图服务能否放在前端，采用canvas的toDataUrl接口生成图片？

### ISSUE THREAD

**Issue by liuming9157** [palxiao/poster-design#39]
如果放在后端，对服务器要求高，且速度慢

**Comment by palxiao** [comment]
html2canvas 的原理是通过 JS 解析目标 DOMTree 然后“翻译”成 Canvas 语法绘制，借由 Canvas API 出图。有几个明显缺点，比如绘制成 Canvas 后图片可能会失真（锯齿、模糊等情况），比如有很多 CSS 特性不支持（如渐变色、文字特效等需要额外开发），还有画布中使用了 SVG 等元素解析困难，所以前端出图在应对复杂场景时工作量难以预估，只有在特别简单的场景下：例如只有图片和最简单的文字构成的海报可以考虑从前端直接出图。服务端 Chrome 截图方式没有这种”翻译“的过程，相当于直接将浏览器作为渲染引擎，能在最少开发成本下保证出图准确性和质量。

其它：[稿定设计出图方案参考](https://xp.palxp.cn/#/articles/1689320598619)
