### ISSUE TITLE
交互体验优化建议

### ISSUE THREAD

**Issue by M-cheng-web** [palxiao/poster-design#4]
在线体验中，切换不同模板无论是否更改过都要弹窗确定，个人感觉这样的体验可以优化一下；只是小小的建议，本人还没有看具体代码实现

**Comment by palxiao** [comment]
感谢建议，这点后期会考虑优化一下的

**Comment by hbignlin** [comment]
能不能直接点击图片进行抠图不想上传，抠图后自动保存到图库中

**Comment by palxiao** [comment]
> 能不能直接点击图片进行抠图不想上传，抠图后自动保存到图库中

该功能已实现。
