### ISSUE TITLE
[求解] 一个关于moveable拖拽出现的问题，始终不得其解

### ISSUE THREAD

**Issue by StoneRyanCn** [palxiao/poster-design#40]
要实现的功能： 在画布显示区，添加一个moveable的resizeable事件，来实现拖拽后画布高度增加或减少的功能

**问题描述：** 在画布(html元素)<div class="design-canvas" data-type="page">这个元素上绑定一个moveable，，但是在拖拽时为了保持moveable选框始终在<div class="design-canvas" data-type="page">的底部显示，结果并没有达到预期效果

**期望达到的预期：** 无论画布是按ctrl+鼠标滚动缩放画布，还是通过最佳效果、25%、50%、75%触缩放等始终将最底部的蓝色拖拽与画布底边保持一致
![image](https://github.com/palxiao/poster-design/assets/15223927/8b5ab8b5-3b69-4f64-bff2-0218e30716eb)

**未达预期情况描述：**
![image](https://github.com/palxiao/poster-design/assets/15223927/28bf612c-b773-4fe3-9263-65fd4e6bc7b4)

![image](https://github.com/palxiao/poster-design/assets/15223927/d25d7d20-6fab-4150-aab2-ba0ac0d72c2d)

**测试的以下两种情况，会达到预期效果：**

情况一： 当在画布中，放置一个左侧的素材图片进入画布以后，达到预期显示效果，且没有任何问题（即在vuex的dWidgets中有一个type: w-image类型的素材时）
情况二： 当在画布中拖拽一个文字素材，且select激活这个文字后，缩放时也会达到预期效果(必须激活选中文字在进行画布调整)

**现在的功能实现方式：**
1. 新写了一个文件`resizeable.vue` ,放在了：src/views/index.vue中，与<Moveable />组件调用放在了一起，为<Resizeable />

2.  resizeable.vue即为moveable.vue的代码，只是作了一些简化

`<template>
  <div id="none" class="moveable__remove-item zk-moveable-style"></div>
</template>
<script lang="ts">
import {defineComponent, nextTick} from 'vue'`

 
`
import Moveable, {EVENTS} from 'moveable' // PROPERTIES, METHODS,
import MoveableHelper from 'moveable-helper'
import {mapGetters, mapActions} from 'vuex'
// import { setTransformAttribute } from '@/common/methods/handleTransform'
import useSelecto from './Selecto'
import store from "@/store";

export default defineComponent({
  setup() {
  },
  data() {
    return {}
  },
  computed: mapGetters(['dSelectWidgets', 'dActiveElement', 'activeMouseEvent', 'showMoveable', 'showRotatable', 'dWidgets', 'updateRect', 'updateSelect', 'guidelines']),
  watch: {
    dWidgets: {
      handler(val) {
        if (store.getters.dWidgets.length > 0) {
          if (this.resizeable.target != '.design-canvas') {
            this.resizeable.target = '.design-canvas'
          }
        } else {
          if (this.resizeable.target !== '[id="none"]') {
            this.resizeable.target = '[id="none"]'
          }
        }
      },
      deep: true,
    },
    updateRect(val) {
      this.resizeable.updateRect()
    },
  },
  mounted() {
    console.log("resizable....")
    // setInterval(() => {
    //   console.log("setinterval.")
    //   this.moveable.updateRect()
    // }, 3000)
    const moveableOptions: any = {
       target: document.querySelector('[id="none"]'),
      zoom: 0.8,
      draggable: false,
      clippable: false, // 裁剪
      throttleDrag: 0,
      resizable: true,
      throttleResize: 0,
      scalable: false,
      throttleScale: 0,
      keepRatio: false,
      rotatable: false,
      throttleRotate: 0,
      renderDirections: ['s'], // ['nw', 'ne', 'sw', 'se'] // 'e'
      pinchable: true, // ["draggable", "resizable", "scalable", "rotatable"]
      origin: false,
      defaultGroupOrigin: '0% 0%',
      // 样式相关
      rotationPosition: 'bottom',
      className: 'resize-moveable-style',
      // -- 吸附对齐 Start --
      snappable: true,
      elementGuidelines: [],
      verticalGuidelines: [],
      horizontalGuidelines: [],
      snapThreshold: 4,
      isDisplaySnapDigit: true,
      snapGap: false,
      snapElement: true,
      snapVertical: true,
      snapHorizontal: true,
      snapCenter: false,
      snapDigit: 0,
      triggerAblesSimultaneously: true,
    }
    const resizeable = new Moveable(document.body, moveableOptions)
    this.resizeable = resizeable
`

`
    resizeable
        .on('resize', (args: any) => {
          const {target, width, height} = args
          store.commit('setShowMoveable', false)
          // 设置画布
          store.dispatch('updatePageData', {
            key: 'height',
            value: height,
            pushHistory: true,
          })

          store.dispatch('updatePageData', {
            key: 'width',
            value: width,
            pushHistory: true,
          })
          target.style.width = width + "px";
          target.style.height = height + "px";

          // const pageElement = document.querySelector("#page-design")
          // pageElement?.scrollTo( 0, document.body.scrollHeight)

        }).on('resizeEnd', () => {
      store.commit('setShowMoveable', true)
    })
  },
  async created() {
    await nextTick()
    const Ele = document.getElementById('page-design')
    Ele?.addEventListener('scroll', () => {
      this.resizeable.updateRect()
    })
  },
  methods: {
    ...mapActions(['updateWidgetData', 'updateWidgetMultiple', 'pushHistory']),
  },
})
</script>

<style lang="less">
@import url('./style/index.less');
</style>
`
  
4. 就是通过监听到调整画布以后，执行resizeable.vue中的watch->updateRect()方法，但是moveable里的updateRect并没有效果, 可是当执行鼠标滚动后，会触发代码中的   
· Ele?.addEventListener('scroll', () => {
      this.moveable.updateRect()
    })
`代码，结果就出现了预期的效果
5. 测试的时候发现每调用一次 watch->updateRect()方法时，显示在画布最下面的那个底部拖拽所在的位置，就是前一步<div class="design-canvas" data-type="page">的高度， 好像是慢了一步，并没有实时显示在当前的画布高度下方，从而没有希望的效果

**Comment by palxiao** [comment]
猜测可能因为画布始终处于默认的“最佳尺寸”导致影响。
<img width="162" alt="image" src="https://github.com/palxiao/poster-design/assets/21021314/887699b4-a645-4dcc-b502-f2af2d3d5346">
这个功能会监听画布尺寸并调整画布自适应，导致尺寸改变后DOM随即发生变化

**Comment by StoneRyanCn** [comment]
当dzoom变化时，改变了这个位置的scale吗？![image](https://github.com/palxiao/poster-design/assets/15223927/634e79a4-d9d0-4c7f-9dc6-e95cd272747c)

第一个问题是： 如果dom的宽高发生变化， 执行moveable实例化后的this.moveable.updateRect() 是不能实时变更这个拖拽与绑定的this.moveable.target保持一致的吗，我在官方文档里没有找到详细的说明。

第二个让我感觉疑惑的问题是： 拖拽一个w-image类型的素材进入画布时， 一切就正常了，我起初以为是wimage.vue有其他的逻辑，查看了源代码， wimage.vue文件是执行了生命周期updated，然后触发   this.$store.commit('updateRect'), 在vuex里执行：
`  updateRect(state: Type.Object, e: any) {
    // 强制刷新操作框
    state.updateRect = Math.random()
  },`

最终moveable.vue里执行了 this.moveable.updateRect(),   我在这里就非常迷惑了， 始终没有找到为什么添加了一个w-image类型的素材，就会正常
我追踪了所有相关的代码，此问题也是困扰了好些天，没有发现问题的本质

**Comment by StoneRyanCn** [comment]
> 猜测可能因为画布始终处于默认的“最佳尺寸”导致影响。 <img alt="image" width="162" src="https://private-user-images.githubusercontent.com/21021314/289503182-887699b4-a645-4dcc-b502-f2af2d3d5346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE5NTgsIm5iZiI6MTcwMjI5MTY1OCwicGF0aCI6Ii8yMTAyMTMxNC8yODk1MDMxODItODg3Njk5YjQtYTY0NS00ZGNjLWI1MDItZjJhZjJkM2Q1MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwNDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ODFiZjhjZGFmODFlZWMyZWQxMGNiZDlkZWVlZGM2ZDA0OTZmNTgxYTIzZjE1NWZkZGY1YmQ0YWU4NjM0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-8MQOxyOLLvkZkdCY7Pl2WbEs24arZA4CfdOJ6hFMY8"> 这个功能会监听画布尺寸并调整画布自适应，导致尺寸改变后DOM随即发生变化


当dzoom变化时，改变了这个位置的scale吗？![image](https://github.com/palxiao/poster-design/assets/15223927/634e79a4-d9d0-4c7f-9dc6-e95cd272747c)

第一个问题是： 如果dom的宽高发生变化， 执行moveable实例化后的this.moveable.updateRect() 后， 不能将this.moveable.target的宽高自动调整吗，我在官方文档里没有找到详细的说明。

第二个让我感觉疑惑的问题是： 拖拽一个w-image类型的素材进入画布时， 一切就正常了，我起初以为是wimage.vue有其他的逻辑，查看了源代码， wimage.vue文件是执行了生命周期updated，然后触发   this.$store.commit('updateRect'), 在vuex里执行：
`  updateRect(state: Type.Object, e: any) {
    // 强制刷新操作框
    state.updateRect = Math.random()
  },`

最终moveable.vue里执行了 this.moveable.updateRect(),   我在这里就非常迷惑了， 始终没有找到为什么添加了一个w-image类型的素材，就会正常
我追踪了所有相关的代码，此问题也是困扰了好些天，没有发现问题的本质

**Comment by StoneRyanCn** [comment]
非常感谢，现在问题已经解决好了。

这个问题是因为拖拽的素材是一个'组合'，
![image](https://github.com/palxiao/poster-design/assets/15223927/1847045a-4e2e-4a21-9d56-180e1807b4dd)，所以在wgroup.vue文件中的生命周期updated中， 添加 `   this.$store.commit('updateRect')`, 这样就可以在定义的文件resizeable.vue里，通过watch监听到`组合`的变化，从而执行this.resizeable.updateRect()就可以了。

**Comment by palxiao** [comment]
👍🏻ok
