### ISSUE TITLE
[求解] 关于draw.vue生成截图下截图片时对【字体解析】的几个疑惑

### ISSUE THREAD

**Issue by StoneRyanCn** [palxiao/poster-design#41]
**问题描述：**  前端调用的API已经变更成我们后端开发的地址了，但是测试下载图片的时候发现，所设置的字体还是默认的字体， 后来发现是因为draw.vue文件有对字体进行接口调用 ，位置是在： `src/utils/widgets/loadFontRule.ts` 中  `const result = await api.material.getFontSub(params, extra)
`

**问题1：(主要问题)**
_该接口(`api.material.getFontSub(params, extra)`)描述的是提取字体子集， 需要传参数: `content`动态生成result，请问咱们后端对该接口逻辑是如何实现的？ 就是对`{
    "code": 200,
    "result": "data:font/woff;base64, ...}`中result返回结果的实现逻辑。能否贴一下咱们后端对这个实现的代码呢？_

**问题2：(次要问题)**
接口调用的是：` https://palxp.cn:8887/design/font_sub?font_id=206822&id=528&content=%E6%B5%8B%E8%AF%95`，不传参数font_id接口返回的是空结果集，而传递font_id值时，返回的是形如：`{
    "code": 200,
    "result": "data:font/woff;base64, ...}` 的数据， 那么这个font_id对应localStorage里的fonts中的oid, 请问这个font_id代码的意思是什么，填与不填是否有什么其他影响？

**问题3：(次要问题)**
最终代码调用了document.head.innerHTML += fontStyles，将所有字体的font-face追回到<head>标签里：
![image](https://github.com/palxiao/poster-design/assets/15223927/9a69208b-eca4-488d-b65c-fe147c1665f7)

由于问题1的逻辑我没有实现，所以直接测试的时候将字体改成了字体的url路径也是可以的(只是有网络的延迟，解析字体要稍等片刻才会有解析),
![image](https://github.com/palxiao/poster-design/assets/15223927/1d899340-46b4-4bfc-ac59-a2d9885da494)
请问咱们现在代码里转为了base64，和直接使用URL作为解析字体的font-family, 这两个是否有区别？

**Comment by palxiao** [comment]
把项目src目录下 supportSubFont: true,  改为 false 即可。这样在下载图片时会加载整个字体文件，本项目实现服务端字体压缩的方案采用的是：https://github.com/ecomfe/fontmin

**Comment by palxiao** [comment]
接口回传加载的字体是base64还是二进制或url理论上没有区别，这里采用base64只是因为参考了稿定的接口所以在本项目中一样处理为base64
