### ISSUE TITLE
能直接本地预览模板生成图片吗？

### ISSUE THREAD

**Issue by CangJieStore** [palxiao/poster-design#44]

**Comment by CangJieStore** [comment]
screenshot的逻辑是否可以直接移植到本地？

**Comment by StoneRyanCn** [comment]
你指的是导出图片的逻辑，不通过node端，而是VUE前端处理？

**Comment by StoneRyanCn** [comment]
我的理解是：screenshot 的出图主要是用puppeteer 这个库，而它是运行于node端的，如果你的意思是放在纯前端，不借助node，那可能这个就行不通。 封面图片的生成是html2canvas,这个可以用在前端出图，但出图的效果不理想。个人见解哈。

**Comment by palxiao** [comment]
screenshot只能运行在node.js环境，如果是本地集成了node环境理论可以运行（如Electron），单纯在浏览器内则不行
