### ISSUE TITLE
linux部署node出图时,puppeteer出现Multiple targets are not supported in headless mode错误

### ISSUE THREAD

**Issue by StoneRyanCn** [palxiao/poster-design#45]
**所遇问题：** 
node出图编译完成后，项目运行下载出图时，报出错误：  Error: Failed to launch the browser process!
0|server  | [0106/164159.036587:ERROR:chrome_main.cc(164)] Multiple targets are not supported in headless mode.

**操作步骤：** 
1. 我是根据文档中安装goole-chrome-stable, 又配置了：` executablePath: /usr/bin/google-chrome-stable`, 安装的google-chrome我发现有好几个()： 

<img width="568" alt="image" src="https://github.com/palxiao/poster-design/assets/15223927/b37c2fe2-bcae-4588-bbf6-5eb38be6747b">
![image](https://github.com/palxiao/poster-design/assets/15223927/a10505a9-49e7-40c5-973b-3be560a8f0dc)

2. 安装完成的最新版本是：  google-chrome-stable-120.0.6099.199-1.x86_64 already installed

3. screenshots在编译完成后，将server.js放在了screenshots/node_module/server.js下，然后执行: `pm2 start node_modules/server.js` ，点击下载出图的时候，就报了 `Multiple targets are not supported in headless mode`
 

代码里只修改了： executablePath: /usr/bin/google-chrome-stable, headless: true,  具体参数如下： 

 browser = await puppeteer.launch({
                    headless: true,
                    executablePath: isDev ? null : executablePath,
                    ignoreHTTPSErrors: true, // 忽略https安全提示
                    args: ['–no-first-run', '–single-process', '–disable-gpu', '–no-zygote', '–disable-dev-shm-usage', '--no-sandbox', '--disable-setuid-sandbox', `--window-size=${width},${height}`], // 优化配置
                    defaultViewport: null,
            })

也查过其他文档，目前没有找到为什么会出现这个问题，请求帮助。

**Comment by palxiao** [comment]
如果手动安装google-chrome总是不顺利的话，也可以尝试在linux上直接安装npm依赖（即不指定executablePath运行），可能npm会自动安装好引入puppeteer的环境，如果还是不行的话，推荐使用docker的方式部署，基本不会出错。
