### ISSUE TITLE
点击文字widget，颜色会消失；还有为什么下载作品不用html2canvas而要用服务器浏览器，是因为想做权限吗？

### ISSUE THREAD

**Issue by qq1311256696** [palxiao/poster-design#46]
点击文字widget，颜色会消失；还有为什么下载作品不用html2canvas而要用服务器浏览器，是因为想做权限吗？

**Comment by qq1311256696** [comment]
<img width="1075" alt="1705027601981" src="https://github.com/palxiao/poster-design/assets/30926001/6426363f-82d8-4ff0-8c4b-e201c74c0ff8">
在designBoard.vue中的handleSelection方法打印的日志，target里面的color已经改了，但是通过uuid查询的widget中的color没有改，是哪里出问题了吗

**Comment by palxiao** [comment]
线上demo没有问题代码就是无误的，确认拉取的是最新代码，并重新安装npm依赖

**Comment by qq1311256696** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
