### ISSUE TITLE
大神，您好，请问微信的登录代码能开源学习学习么，搞了好久有问题，求开源学习学习，膜拜大神

### ISSUE THREAD

**Issue by arraycto** [palxiao/poster-design#47]
大神，您好，请问微信的登录代码能开源学习学习么，搞了好久有问题，求开源学习学习，膜拜大神

**Comment by palxiao** [comment]
涉及后端代码，不方便公开。线上实现的非微信常规扫码登录，是利用小程序openid登录方式，感兴趣的话后面有时间我再写篇文章详细介绍实现过程。
