### ISSUE TITLE
无法上传资源，或无法登录

### ISSUE THREAD

**Issue by coracoo** [palxiao/poster-design#48]
大佬好，通过新建项目以后，选择我的-资源管理-所有图片都为failed，选择图片上传提示成功，但是依旧无法看到，且没有看到日志信息，请问如何处理？看了下在线版本，似乎是没有微信登录导致的？

以下是我新建项目的方式：
最后npm run serve后无法将端口映射到外，所以换了npx，不知道是否是这个原因？同时，我新使用node16.8.1生成了一个docker镜像，部署后也是同样的问题。

期盼解答，十分感谢
```
FROM node:16.18.1 AS builder
RUN npm config set registry https://registry.npmmirror.com
RUN apt-get update && apt-get -y dist-upgrade
WORKDIR /app
COPY ./poster-design /app
RUN  node -v && npm install && npm i ts-node-dev -D && npm i --save puppeteer && npm i --save images
EXPOSE 3000
CMD ["npm", "run", "prepared"]
CMD ["npx", "vite", "serve","--host", "0.0.0.0"]
```

**Comment by palxiao** [comment]
非项目运行或代码问题，七牛云资源为避免消耗过大设置了refer，后续可能会重构上传组件。暂时可以使用回环地址即能正常显示图片：http://127.0.0.1:3000/home
