### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by hbignlin** [palxiao/poster-design#5]
nodejs 用 V16 报错没有 src/config,老哥根本跑不起来啊。
试了17 好了项目直接起不来了

**Comment by palxiao** [comment]
误删了，已恢复config.ts文件，可以再试下

**Comment by hbignlin** [comment]
提交中我找到config.ts恢复了，然后报错router 错误
| |
hbinglin
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Shawn ***@***.***> |
| 发送日期 | 2023年7月26日 00:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [palxiao/poster-design] 跑不起来 (Issue #5) |

误删了，已恢复config.ts文件，可以再试下

**Comment by palxiao** [comment]
> 提交中我找到config.ts恢复了，然后报错router 错误 | | hbinglin | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | Shawn ***@***.***> | | 发送日期 | 2023年7月26日 00:43 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [palxiao/poster-design] 跑不起来 (Issue #5) | 误删了，已恢复config.ts文件，可以再试下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

是浏览器控制台的报错还是项目起不来？如果项目本地能正常运行的话前端路由报错应该没关系的，或者你可以改成hash路由试试，项目中使用的是history模式。
