### ISSUE TITLE
单行文本下载作品的图片变成多行了

### ISSUE THREAD

**Issue by zjc2233** [palxiao/poster-design#50]
![1134](https://github.com/palxiao/poster-design/assets/43945226/bc9244bb-a5a5-4ec6-9b50-82707dbdf2b2)
<img width="708" alt="1135" src="https://github.com/palxiao/poster-design/assets/43945226/22f54c18-b63d-431c-8787-3082b38cb961">
希望服务端渲染的时候能继续保持单行文本

**Comment by palxiao** [comment]
已修复。https://github.com/palxiao/poster-design/commit/eb562af40989915cd719183ac8fae078b7bbd8ef#diff-2f143d90a110c80ab8f3f61f56796e18122dd0fb19f0703a90391eb57b9bca1c
