### ISSUE TITLE
点击文字编辑颜色变成了白色

### ISSUE THREAD

**Issue by ychy00001** [palxiao/poster-design#54]
拉下来最新的代码，启动后测试，发现编辑文字，进入页面是正常的。点击文字元素，文字就变成了白色。
自己捋了下代码，designBoard.vue中的handleSelection处理选中元素的逻辑。下图是打印的信息，在选中之前就变了颜色。实在找不到问题所在。求助

![WX20240229-182344](https://github.com/palxiao/poster-design/assets/15539411/d581bdb1-181e-41c9-8b3b-d95e8416f41e)
![image](https://github.com/palxiao/poster-design/assets/15539411/0af8eeea-4ddf-43ff-ace2-dc5b71aa1560)

**Comment by palxiao** [comment]
可能需要重新安装一下npm依赖

**Comment by ychy00001** [comment]
> 可能需要重新安装一下npm依赖

下午重新拉的依赖，整个目录都是新的。我大概找到问题了。colorSelect模块中像是@palxp/color-picker组件问题。
state.innerColor = "#c53b3aff"这个颜色就不行 换成”#c53b3aFF“这样就可以了。
修正了下代码，下图这样就好使了
![image](https://github.com/palxiao/poster-design/assets/15539411/740e21cc-768f-476b-a9d4-6bbfe05bc06a)

**Comment by needou** [comment]
确实是这个组件的问题，对于小写的16进制支持问题

**Comment by palxiao** [comment]
pr已合并。

不过很奇怪我这边找了几台电脑都复现不了，之前别人遇到这个问题是重新安装过包依赖就可以了，为此我还特意把 package.lock 文件上传了一遍。

**Comment by ychy00001** [comment]
> pr已合并。
> 
> 不过很奇怪我这边找了几台电脑都复现不了，之前别人遇到这个问题是重新安装过包依赖就可以了，为此我还特意把 package.lock 文件上传了一遍。

有些问题就特别玄学，环境因素太多了，我最开始npm install下载那个puppeteer拉不下来，换成yarn install就好使了，都是淘宝镜像，反正解决了。
MacOS BigSur 11.2.3
```
$ cnpm --version 
cnpm@9.0.1 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@8.19.4 (/usr/local/lib/node_modules/cnpm/node_modules/npm/index.js)
node@18.4.0 (/usr/local/Cellar/node/18.4.0/bin/node)
npminstall@7.5.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local
darwin x64 20.3.0
registry=https://registry.npmmirror.com
```
