### ISSUE TITLE
这确定不是抄袭vue-fabric-editor？开源也要注明一下从哪来的灵感吧，未免也太不尊重作者。

### ISSUE THREAD

**Issue by CherishMvp** [palxiao/poster-design#6]

**Comment by CherishMvp** [comment]
既然有过交流，那就是灵感和创意都来自于他人，现在的人真的是想钱想成名疯了

发自我的 iPhone

在 2023年7月26日，09:55，Shawn Phang ***@***.***> 写道：

﻿

我跟这个项目的作者半年多前就有过交流，人家是基于fabric.js开发，技术实现上没有半点相似度，不知道你这油然而生的”正义感“是从何而来的。至于图片编辑器本身，朋友，建议了解一下市面上成熟的商业产品再发表你的言论吧？不然也请先至少体验一下稿定设计好吗。

**Comment by palxiao** [comment]
你说的都对，像你这样充满戾气的我也是头一次见，感谢你给了我不少的“灵感”，不过我认为你喷的话还是缺乏“创意”，不太适合当键盘侠，不如学学如何好好说话吧，言尽于此。附上该项目作者以前在我帖子中的留言截图：<img width="778" alt="image" src="https://github.com/palxiao/poster-design/assets/21021314/683a8889-39ee-4e9b-9df6-b244a37562a0">
<img width="442" alt="image" src="https://github.com/palxiao/poster-design/assets/21021314/6d3f0993-9197-49a4-bedb-97c7867d9092">

**Comment by jujusharp** [comment]
@CherishMvp 我一个旁观者看到这个，觉得吧，既然是技术交流，就不要戾气这么重，大家好好交流，把疑问点讲清楚，作者在readme中说得很清楚了，UI交互设计是仿照的稿定设计的产品。至于技术实现原理，如果你看过vue-fabric-editor的源码的话，你就会知道技术实现完全是两种不同的方式。

**Comment by swordsman-coder** [comment]
@CherishMvp 同样我也是作为旁观者，如果你单纯的想发泄，就不要找借口。如果你是想技术交流，就先好好看，然后好好说话，提出你的问题。

## 1、灵感这块
作者在readme和一些文章都写了，仿的搞定的。
<img width="557" alt="image" src="https://github.com/palxiao/poster-design/assets/16441180/1ad397eb-db7b-40de-b37b-afc39b7787b7">

## 2、技术这块
技术这块正如 @jujusharp所说，你最好先去看看vue-fabric-editor的源码,他是使用的fabricjs。而作者这个是使用dom，出图使用的无头浏览器Puppeteer，服务端出图。

**给自己一份克制，给别人一份理解。**

**Comment by CherishMvp** [comment]
好的，谢谢大家指正我在此处提出的错误，以后会更加注重自己的措辞，保持社区良好的氛围。我再次向作者表示道歉，并关闭此issue。抱歉，给大家带来不好的影响。 @palxiao

**Comment by hopkinson** [comment]
笑话
