### ISSUE TITLE
手动进 screenshot 目录安装依赖并启动服务

### ISSUE THREAD

**Issue by hbignlin** [palxiao/poster-design#7]
安装依赖也是执行这个命令吗？npm run prepared
还是执行 npm install

**Comment by palxiao** [comment]
npm install 安装依赖和 npm run dev启动。npm run prepared 与 npm run serve 是同时运行两个命令的快捷指令，正常运行的话是没有问题的，但在windows下的CMD这类没有shell的环境可能不会成功
