### ISSUE TITLE
对元素缩放时，选中框有几条边超出边框了，是bug？

### ISSUE THREAD

**Issue by JoshuaZhengsurp** [palxiao/poster-design#75]
![image](https://github.com/palxiao/poster-design/assets/99573384/e0002ce6-8a37-4407-9b49-d2d9d3415a18)

**Comment by JeremyYu-cn** [comment]
能把复现的过程描述一下吗，我没有复现这个问题~

**Comment by palxiao** [comment]
预期以外的效果，但不影响功能，后期优化
