### ISSUE TITLE
在点击下载时，一共会有6个tab打开

### ISSUE THREAD

**Issue by 1024bit** [palxiao/poster-design#8]
很赞！
我的问题是：在点击下载时，一共会有6个tab打开，且只有最后一个正常访问，这是什么问题？
感谢！

**Comment by palxiao** [comment]
没有问题，这是正常的。在 puppeteer.launch 中我设置了一些 args 用于优化浏览器在无头模式(headless)下的加载性能，而本地跑项目时无头模式被我默认为关闭，所以你才会看到自动调起一个Chrome，而因为其中传入的某些参数可能并不能在这种模式下生效，所以出现了一些tab页的提示，它们并非真正的标签页实例。
